
# Setup
title:               Requestly
email:               requestly.extension@gmail.com
tagline:             Chrome and Firefox extension to modify network requests
url:                 "" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Sachin Jain
  url:               https://twitter.com/sachinjain024
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: requestly
twitter_username: requestly64
# instagram_username: kevin/
facebook: requestly/
# linkedin_username: xiaoying
# dribbble_username: Xiaoying

# Custom vars
github:
  repo:              https://github.com/requestly/requestly-browser-extension

requestly:
  firefox:
    download_url: http://requestly.in/public/firefox/requestly-latest.xpi
  chrome:
    download_url: https://chrome.google.com/webstore/detail/requestly/mdnleldcmiljblolnjhpnblkcekpdkpa

gallery:
  item1:
    card1:
      title: Rule Types Screen
      desc: Requestly supports different rule types to achieve different use cases
    card2:
      title: Rule Index Screen
      desc: Lists all the rules created so far with quick activation and deactivation of rules.
  item2:
    card1:
      title: Redirect Rule Screen
      desc: Redirect Url(s) matching particular pattern to provided destination url (Supports Regex)
    card2:
      title: Replace Rule Screen
      desc: Replace some part in a Url with different string (e.g. Change query parameter values, Change host names)
  item3:
    card1:
      title: Headers Rule Screen
      desc: Modify Request and Response Headers. Note - Modifications in response headers are not visible in chrome dev tools.
    card2:
      title: Share Rules dialog
      desc: Select some rules and click on share icon to generate a public Url.

paypalMe: https://paypal.me/sachinjain024

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty
