
# Setup
title:               Requestly
email:               requestly.extension@gmail.com
tagline:             Chrome and Firefox extension to modify network requests
url:                 "" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Sachin Jain
  url:               https://twitter.com/sachinjain024
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: requestly
twitter_username: requestly64
# instagram_username: kevin/
facebook: requestly/
# linkedin_username: xiaoying
# dribbble_username: Xiaoying

# Custom vars
version:             4.2.0
github:
  repo:              https://github.com/requestly/requestly-browser-extension

requestly:
  firefox:
    download_url: https://dl.dropboxusercontent.com/u/71743966/requestly/firefox/requestly-4.1.9.xpi
  chrome:
    download_url: https://chrome.google.com/webstore/detail/requestly/mdnleldcmiljblolnjhpnblkcekpdkpa


# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty
